[book]
title = "Hac√© Documentation"
authors = ["Roberto Alsina"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ralsina/hace"
edit-url-template = "https://github.com/ralsina/hace/edit/main/docs/{path}"

[output.html.search]
enable = true

[output.html.playground]
editable = false
